/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.icshelper;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IcsHelperStandaloneSetup extends IcsHelperStandaloneSetupGenerated {

	public static void doSetup() {
		new IcsHelperStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
