/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.icshelper.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IcsHelperAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/icshelper/parser/antlr/internal/InternalIcsHelper.tokens");
	}
}
