/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.icshelper.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.icshelper.parser.antlr.internal.InternalIcsHelperParser;
import org.xtext.example.icshelper.services.IcsHelperGrammarAccess;

public class IcsHelperParser extends AbstractAntlrParser {

	@Inject
	private IcsHelperGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIcsHelperParser createParser(XtextTokenStream stream) {
		return new InternalIcsHelperParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public IcsHelperGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IcsHelperGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
