/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.icshelper.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIcsHelperScopeProvider extends DelegatingScopeProvider {
}
