/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.icshelper.icsHelper.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.icshelper.icsHelper.IcsHelperPackage;
import org.xtext.example.icshelper.icsHelper.MergeCommand;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Merge Command</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.icshelper.icsHelper.impl.MergeCommandImpl#getSchedules <em>Schedules</em>}</li>
 *   <li>{@link org.xtext.example.icshelper.icsHelper.impl.MergeCommandImpl#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MergeCommandImpl extends CommandImpl implements MergeCommand
{
  /**
   * The cached value of the '{@link #getSchedules() <em>Schedules</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchedules()
   * @generated
   * @ordered
   */
  protected EList<String> schedules;

  /**
   * The default value of the '{@link #getTarget() <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected static final String TARGET_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected String target = TARGET_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MergeCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IcsHelperPackage.Literals.MERGE_COMMAND;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getSchedules()
  {
    if (schedules == null)
    {
      schedules = new EDataTypeEList<String>(String.class, this, IcsHelperPackage.MERGE_COMMAND__SCHEDULES);
    }
    return schedules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTarget(String newTarget)
  {
    String oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IcsHelperPackage.MERGE_COMMAND__TARGET, oldTarget, target));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IcsHelperPackage.MERGE_COMMAND__SCHEDULES:
        return getSchedules();
      case IcsHelperPackage.MERGE_COMMAND__TARGET:
        return getTarget();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IcsHelperPackage.MERGE_COMMAND__SCHEDULES:
        getSchedules().clear();
        getSchedules().addAll((Collection<? extends String>)newValue);
        return;
      case IcsHelperPackage.MERGE_COMMAND__TARGET:
        setTarget((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IcsHelperPackage.MERGE_COMMAND__SCHEDULES:
        getSchedules().clear();
        return;
      case IcsHelperPackage.MERGE_COMMAND__TARGET:
        setTarget(TARGET_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IcsHelperPackage.MERGE_COMMAND__SCHEDULES:
        return schedules != null && !schedules.isEmpty();
      case IcsHelperPackage.MERGE_COMMAND__TARGET:
        return TARGET_EDEFAULT == null ? target != null : !TARGET_EDEFAULT.equals(target);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (schedules: ");
    result.append(schedules);
    result.append(", target: ");
    result.append(target);
    result.append(')');
    return result.toString();
  }

} //MergeCommandImpl
