/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.icshelper.icsHelper;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.icshelper.icsHelper.IcsHelperPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
} // Command
