/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.icshelper.icsHelper;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.icshelper.icsHelper.IcsHelperFactory
 * @model kind="package"
 * @generated
 */
public interface IcsHelperPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "icsHelper";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/icshelper/IcsHelper";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "icsHelper";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IcsHelperPackage eINSTANCE = org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.icshelper.icsHelper.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.icshelper.icsHelper.impl.ModelImpl
   * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.icshelper.icsHelper.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.icshelper.icsHelper.impl.CommandImpl
   * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.icshelper.icsHelper.impl.CreateCommandImpl <em>Create Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.icshelper.icsHelper.impl.CreateCommandImpl
   * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getCreateCommand()
   * @generated
   */
  int CREATE_COMMAND = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND__NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND__EVENTS = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Create Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.icshelper.icsHelper.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.icshelper.icsHelper.impl.EventImpl
   * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__START_TIME = 1;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__END_TIME = 2;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__LOCATION = 3;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.icshelper.icsHelper.impl.SplitCommandImpl <em>Split Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.icshelper.icsHelper.impl.SplitCommandImpl
   * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getSplitCommand()
   * @generated
   */
  int SPLIT_COMMAND = 4;

  /**
   * The feature id for the '<em><b>Schedule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_COMMAND__SCHEDULE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Criteria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_COMMAND__CRITERIA = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Split Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.icshelper.icsHelper.impl.MergeCommandImpl <em>Merge Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.icshelper.icsHelper.impl.MergeCommandImpl
   * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getMergeCommand()
   * @generated
   */
  int MERGE_COMMAND = 5;

  /**
   * The feature id for the '<em><b>Schedules</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MERGE_COMMAND__SCHEDULES = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MERGE_COMMAND__TARGET = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Merge Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MERGE_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.icshelper.icsHelper.impl.ModifyCommandImpl <em>Modify Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.icshelper.icsHelper.impl.ModifyCommandImpl
   * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getModifyCommand()
   * @generated
   */
  int MODIFY_COMMAND = 6;

  /**
   * The feature id for the '<em><b>Schedule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__SCHEDULE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__EVENT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__TIME = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__VALUE = COMMAND_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Modify Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.icshelper.icsHelper.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.icshelper.icsHelper.Model#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Model#getCommands()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Commands();

  /**
   * Returns the meta object for class '{@link org.xtext.example.icshelper.icsHelper.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.icshelper.icsHelper.CreateCommand <em>Create Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Command</em>'.
   * @see org.xtext.example.icshelper.icsHelper.CreateCommand
   * @generated
   */
  EClass getCreateCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.CreateCommand#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.icshelper.icsHelper.CreateCommand#getName()
   * @see #getCreateCommand()
   * @generated
   */
  EAttribute getCreateCommand_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.icshelper.icsHelper.CreateCommand#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see org.xtext.example.icshelper.icsHelper.CreateCommand#getEvents()
   * @see #getCreateCommand()
   * @generated
   */
  EReference getCreateCommand_Events();

  /**
   * Returns the meta object for class '{@link org.xtext.example.icshelper.icsHelper.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.Event#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Event#getStartTime()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_StartTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.Event#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Event#getEndTime()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_EndTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.Event#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see org.xtext.example.icshelper.icsHelper.Event#getLocation()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Location();

  /**
   * Returns the meta object for class '{@link org.xtext.example.icshelper.icsHelper.SplitCommand <em>Split Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Split Command</em>'.
   * @see org.xtext.example.icshelper.icsHelper.SplitCommand
   * @generated
   */
  EClass getSplitCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.SplitCommand#getSchedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Schedule</em>'.
   * @see org.xtext.example.icshelper.icsHelper.SplitCommand#getSchedule()
   * @see #getSplitCommand()
   * @generated
   */
  EAttribute getSplitCommand_Schedule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.SplitCommand#getCriteria <em>Criteria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Criteria</em>'.
   * @see org.xtext.example.icshelper.icsHelper.SplitCommand#getCriteria()
   * @see #getSplitCommand()
   * @generated
   */
  EAttribute getSplitCommand_Criteria();

  /**
   * Returns the meta object for class '{@link org.xtext.example.icshelper.icsHelper.MergeCommand <em>Merge Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Merge Command</em>'.
   * @see org.xtext.example.icshelper.icsHelper.MergeCommand
   * @generated
   */
  EClass getMergeCommand();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.icshelper.icsHelper.MergeCommand#getSchedules <em>Schedules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Schedules</em>'.
   * @see org.xtext.example.icshelper.icsHelper.MergeCommand#getSchedules()
   * @see #getMergeCommand()
   * @generated
   */
  EAttribute getMergeCommand_Schedules();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.MergeCommand#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.xtext.example.icshelper.icsHelper.MergeCommand#getTarget()
   * @see #getMergeCommand()
   * @generated
   */
  EAttribute getMergeCommand_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.example.icshelper.icsHelper.ModifyCommand <em>Modify Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modify Command</em>'.
   * @see org.xtext.example.icshelper.icsHelper.ModifyCommand
   * @generated
   */
  EClass getModifyCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.ModifyCommand#getSchedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Schedule</em>'.
   * @see org.xtext.example.icshelper.icsHelper.ModifyCommand#getSchedule()
   * @see #getModifyCommand()
   * @generated
   */
  EAttribute getModifyCommand_Schedule();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.icshelper.icsHelper.ModifyCommand#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see org.xtext.example.icshelper.icsHelper.ModifyCommand#getEvent()
   * @see #getModifyCommand()
   * @generated
   */
  EReference getModifyCommand_Event();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.ModifyCommand#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.example.icshelper.icsHelper.ModifyCommand#getTime()
   * @see #getModifyCommand()
   * @generated
   */
  EAttribute getModifyCommand_Time();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.icshelper.icsHelper.ModifyCommand#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.icshelper.icsHelper.ModifyCommand#getValue()
   * @see #getModifyCommand()
   * @generated
   */
  EAttribute getModifyCommand_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IcsHelperFactory getIcsHelperFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.icshelper.icsHelper.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.icshelper.icsHelper.impl.ModelImpl
     * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMMANDS = eINSTANCE.getModel_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.example.icshelper.icsHelper.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.icshelper.icsHelper.impl.CommandImpl
     * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.icshelper.icsHelper.impl.CreateCommandImpl <em>Create Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.icshelper.icsHelper.impl.CreateCommandImpl
     * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getCreateCommand()
     * @generated
     */
    EClass CREATE_COMMAND = eINSTANCE.getCreateCommand();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE_COMMAND__NAME = eINSTANCE.getCreateCommand_Name();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_COMMAND__EVENTS = eINSTANCE.getCreateCommand_Events();

    /**
     * The meta object literal for the '{@link org.xtext.example.icshelper.icsHelper.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.icshelper.icsHelper.impl.EventImpl
     * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__START_TIME = eINSTANCE.getEvent_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__END_TIME = eINSTANCE.getEvent_EndTime();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__LOCATION = eINSTANCE.getEvent_Location();

    /**
     * The meta object literal for the '{@link org.xtext.example.icshelper.icsHelper.impl.SplitCommandImpl <em>Split Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.icshelper.icsHelper.impl.SplitCommandImpl
     * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getSplitCommand()
     * @generated
     */
    EClass SPLIT_COMMAND = eINSTANCE.getSplitCommand();

    /**
     * The meta object literal for the '<em><b>Schedule</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPLIT_COMMAND__SCHEDULE = eINSTANCE.getSplitCommand_Schedule();

    /**
     * The meta object literal for the '<em><b>Criteria</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPLIT_COMMAND__CRITERIA = eINSTANCE.getSplitCommand_Criteria();

    /**
     * The meta object literal for the '{@link org.xtext.example.icshelper.icsHelper.impl.MergeCommandImpl <em>Merge Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.icshelper.icsHelper.impl.MergeCommandImpl
     * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getMergeCommand()
     * @generated
     */
    EClass MERGE_COMMAND = eINSTANCE.getMergeCommand();

    /**
     * The meta object literal for the '<em><b>Schedules</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MERGE_COMMAND__SCHEDULES = eINSTANCE.getMergeCommand_Schedules();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MERGE_COMMAND__TARGET = eINSTANCE.getMergeCommand_Target();

    /**
     * The meta object literal for the '{@link org.xtext.example.icshelper.icsHelper.impl.ModifyCommandImpl <em>Modify Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.icshelper.icsHelper.impl.ModifyCommandImpl
     * @see org.xtext.example.icshelper.icsHelper.impl.IcsHelperPackageImpl#getModifyCommand()
     * @generated
     */
    EClass MODIFY_COMMAND = eINSTANCE.getModifyCommand();

    /**
     * The meta object literal for the '<em><b>Schedule</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODIFY_COMMAND__SCHEDULE = eINSTANCE.getModifyCommand_Schedule();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY_COMMAND__EVENT = eINSTANCE.getModifyCommand_Event();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODIFY_COMMAND__TIME = eINSTANCE.getModifyCommand_Time();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODIFY_COMMAND__VALUE = eINSTANCE.getModifyCommand_Value();

  }

} //IcsHelperPackage
